DELIMITER $$
CREATE DEFINER=`root`@`localhost` PROCEDURE `INSERT_DATA_ICE`()
BEGIN
	DECLARE _NOMBRE_ELECCION TEXT;
    DECLARE _AÑO_ELECCION INT;
    DECLARE _PAIS TEXT;
    DECLARE _REGION TEXT;
    DECLARE _DEPTO TEXT;
    DECLARE _MUNICIPIO TEXT;
    DECLARE _PARTIDO TEXT;
    DECLARE _NOMBRE_PARTIDO TEXT;
    DECLARE _SEXO TEXT;
    DECLARE _RAZA TEXT;
    DECLARE _ANALFABETOS INT;
	DECLARE _ALFABETOS INT; 
	DECLARE _PRIMARIA INT; 
    DECLARE _NIVEL_MEDIO INT;
    DECLARE _UNIVERSITARIOS INT;
    
    DECLARE _ID_PAIS INT;
	DECLARE _ID_REGION INT;
    DECLARE _ID_DEPARTAMENTO INT;
    DECLARE _ID_MUNICIPIO INT;
    DECLARE _ID_PARTIDO INT;
    DECLARE _ID_RAZA INT;
    DECLARE _ID_ELECCION INT;
    DECLARE _ID_POBLACION INT;

	DECLARE fin BOOLEAN DEFAULT FALSE;

	 DECLARE cur CURSOR FOR
        SELECT NOMBRE_ELECCION
				,AÑO_ELECCION
                ,PAIS
                ,REGION 
				,DEPTO 
				,MUNICIPIO
				,PARTIDO 
				,NOMBRE_PARTIDO
				,SEXO 
				,RAZA
				,ANALFABETOS
				,ALFABETOS  
				,PRIMARIA  
				,NIVEL_MEDIO 
				,UNIVERSITARIOS
		FROM ICE_FUENTE ;

    -- Manejador para el final del cursor
    DECLARE CONTINUE HANDLER FOR NOT FOUND
        SET fin = TRUE;

    -- Abrir el cursor
    OPEN cur;
    loop_inicio: WHILE NOT fin DO
        -- Obtener los valores de la fila actual del cursor
        FETCH cur INTO _NOMBRE_ELECCION
				,_AÑO_ELECCION
                ,_PAIS
                ,_REGION
                ,_DEPTO 
				,_MUNICIPIO
				,_PARTIDO 
				,_NOMBRE_PARTIDO
                ,_SEXO 
				,_RAZA
                ,_ANALFABETOS
				,_ALFABETOS
                ,_PRIMARIA  
				,_NIVEL_MEDIO 
				,_UNIVERSITARIOS;
                
		##llenar la tabla pais
		IF (SELECT COUNT(*) FROM PAIS WHERE NOMBRE = _PAIS ) > 0 THEN
			SELECT  ID_PAIS INTO _ID_PAIS FROM PAIS WHERE NOMBRE = _PAIS;
		ELSE 
			INSERT INTO PAIS(NOMBRE) VALUES(_PAIS);
        END IF; 
        ##llenar la tabla region
        IF (SELECT COUNT(*) FROM region WHERE NOMBRE = _REGION AND ID_PAIS = _ID_PAIS ) > 0 THEN
			SELECT  ID_REGION INTO _ID_REGION FROM REGION WHERE NOMBRE = _REGION AND ID_PAIS = _ID_PAIS;
		ELSE 
			INSERT INTO REGION(NOMBRE,ID_PAIS) VALUES(_REGION,_ID_PAIS);
        END IF; 
        
         ##llenar la tabla DEPARTAMENTO
        IF (SELECT COUNT(*) FROM DEPARTAMENTO WHERE NOMBRE = _DEPTO AND ID_REGION = _ID_REGION ) > 0 THEN
			SELECT  ID_DEPARTAMENTO INTO _ID_DEPARTAMENTO FROM DEPARTAMENTO WHERE NOMBRE = _DEPTO AND ID_REGION = _ID_REGION;
		ELSE 
			INSERT INTO DEPARTAMENTO(NOMBRE,ID_REGION) VALUES(_DEPTO,_ID_REGION);
        END IF; 
        
        ##llenar la tabla MUNICIPIO
        IF (SELECT COUNT(*) FROM MUNICIPIO WHERE NOMBRE = _MUNICIPIO AND ID_DEPARTAMENTO = _ID_DEPARTAMENTO ) > 0 THEN
			SELECT  ID_MUNICIPIO INTO _ID_MUNICIPIO FROM MUNICIPIO WHERE NOMBRE = _MUNICIPIO AND ID_DEPARTAMENTO = _ID_DEPARTAMENTO;
		ELSE 
			INSERT INTO MUNICIPIO(NOMBRE,ID_DEPARTAMENTO) VALUES(_MUNICIPIO,_ID_DEPARTAMENTO);
        END IF;
        
        ##llenar la tabla PARTIDO POLITICO 
        IF (SELECT COUNT(*) FROM PARTIDO_POLITICO WHERE NOMBRE_CORTO = _PARTIDO ) > 0 THEN
			SELECT  ID_PARTIDO INTO _ID_PARTIDO FROM PARTIDO_POLITICO WHERE NOMBRE_CORTO = _PARTIDO;
		ELSE 
			INSERT INTO PARTIDO_POLITICO(NOMBRE_CORTO,NOMBRE_PARTIDO) VALUES(_PARTIDO,_NOMBRE_PARTIDO);
        END IF;
        
         ##llenar la tabla RAZA
        IF (SELECT COUNT(*) FROM RAZA WHERE NOMBRE = _RAZA ) > 0 THEN
			SELECT  ID_RAZA INTO _ID_RAZA FROM RAZA WHERE NOMBRE = _RAZA;
		ELSE 
			INSERT INTO RAZA(NOMBRE) VALUES(_RAZA);
        END IF;
        
       ##LLENAR TABLA ELECCION 
        INSERT INTO ELECCION(AÑO,NOMBRE_ELECCION,ID_MUNICIPIO,ID_PUESTO)
					VALUES(_AÑO_ELECCION,_NOMBRE_ELECCION,_ID_MUNICIPIO,1);
		SELECT last_insert_id() INTO _ID_ELECCION;
        
         #LLENAR TABLA POBLACION
        INSERT INTO POBLACION(SEXO,ID_RAZA,PRIMARIA,NIVEL_MEDIO,UNIVERTSITARIOS,ANALFABETOS,ALFABETOS)
        VALUES(_SEXO,_ID_RAZA,_PRIMARIA,_NIVEL_MEDIO,_UNIVERSITARIOS,_ANALFABETOS,_ALFABETOS);
        SELECT last_insert_id() INTO _ID_POBLACION;
        
        #LLENAR VOTACION 
        INSERT INTO VOTACION(ID_POBLACION,ID_ELECCION,ID_PARTIDO,VOTOS_OBTENIDOS)
				VALUES(_ID_POBLACION,_ID_ELECCION,_ID_PARTIDO,(_ALFABETOS + _ANALFABETOS));
        
       
    END WHILE loop_inicio;
    CLOSE cur;
    

END$$
DELIMITER ;
