CREATE TABLE `PAIS` (
  `ID_PAIS` INT PRIMARY KEY,
  `NOMBRE` VARCHAR(100)
);

CREATE TABLE `REGION` (
  `ID_REGION` INT PRIMARY KEY,
  `NOMBRE` VARCHAR(100),
  `ID_PAIS` INT
);

CREATE TABLE `DEPARTAMENTO` (
  `ID_DEPARTAMENTO` INT PRIMARY KEY,
  `NOMBRE` VARCHAR(100),
  `ID_REGION` INT
);

CREATE TABLE `MUNICIPIO` (
  `ID_MUNICIPIO` INT PRIMARY KEY,
  `NOMBRE` VARCHAR(100),
  `ID_DEPARTAMENTO` INT
);

CREATE TABLE `POBLACION` (
  `ID_POBLACION` INT PRIMARY KEY,
  `SEXO` VARCHAR(30),
  `ID_RAZA` INT,
  `PRIMARIA` INT,
  `NIVEL_MEDIO` INT,
  `UNIVERTSITARIOS` INT,
  `ANALFABETOS` INT,
  `ALFABETOS` INT
);

CREATE TABLE `ELECCION` (
  `ID_ELECCION` INT AUTO_INCREMENT PRIMARY KEY,
  `AÑO` INT,
  `NOMBRE_ELECCION` VARCHAR(100),
  `ID_MUNICIPIO` INT,
  `ID_PUESTO` INT
);

DROP TABLE ELECCION;

CREATE TABLE `PARTIDO_POLITICO` (
  `ID_PARTIDO` INT PRIMARY KEY,
  `NOMBRE_CORTO` VARCHAR(255),
  `NOMBRE_PARTIDO` VARCHAR(255)
);

CREATE TABLE `VOTACION` (
  `ID_VOTACION` INT AUTO_INCREMENT PRIMARY KEY,
  `ID_POBLACION` INT,
  `ID_ELECCION` INT,
  `ID_PARTIDO` INT,
  `VOTOS_OBTENIDOS` INT
);

DROP TABLE VOTACION;

CREATE TABLE `RAZA` (
  `ID_RAZA` INT PRIMARY KEY,
  `NOMBRE` VARCHAR(100)
);

CREATE TABLE `PUESTO` (
  `ID_PUESTO` INT PRIMARY KEY,
  `NOMBRE_PUESTO` VARCHar(200)
);

ALTER TABLE `POBLACION` ADD FOREIGN KEY (`ID_RAZA`) REFERENCES `RAZA` (`ID_RAZA`);

ALTER TABLE `VOTACION` ADD FOREIGN KEY (`ID_POBLACION`) REFERENCES `POBLACION` (`ID_POBLACION`);

ALTER TABLE `VOTACION` ADD FOREIGN KEY (`ID_PARTIDO`) REFERENCES `PARTIDO_POLITICO` (`ID_PARTIDO`);

ALTER TABLE `REGION` ADD FOREIGN KEY (`ID_PAIS`) REFERENCES `PAIS` (`ID_PAIS`);

ALTER TABLE `DEPARTAMENTO` ADD FOREIGN KEY (`ID_REGION`) REFERENCES `REGION` (`ID_REGION`);

ALTER TABLE `MUNICIPIO` ADD FOREIGN KEY (`ID_DEPARTAMENTO`) REFERENCES `DEPARTAMENTO` (`ID_DEPARTAMENTO`);

ALTER TABLE `VOTACION` ADD FOREIGN KEY (`ID_ELECCION`) REFERENCES `ELECCION` (`ID_ELECCION`);

ALTER TABLE `ELECCION` ADD FOREIGN KEY (`ID_PUESTO`) REFERENCES `PUESTO` (`ID_PUESTO`);

ALTER TABLE `ELECCION` ADD FOREIGN KEY (`ID_MUNICIPIO`) REFERENCES `MUNICIPIO` (`ID_MUNICIPIO`);

